import type { PersonalDocument } from "./types";

export const initialDocuments: PersonalDocument[] = [
  {
    id: "passport",
    title: "Загранпаспорт",
    category: "travel",
    status: "ready",
    expiresAt: "12.08.2031",
    contact: "",
    location: "Оригинал · ручная кладь",
    note: "Сделать две бумажные копии",
  },
  {
    id: "visa",
    title: "Студенческая виза X1",
    category: "travel",
    status: "preparing",
    expiresAt: "31.08.2026",
    contact: "Визовый центр",
    location: "",
    note: "Проверить срок въезда после выдачи",
  },
  {
    id: "admission",
    title: "Admission Notice",
    category: "study",
    status: "ready",
    expiresAt: "31.12.2026",
    contact: "International Office",
    location: "Облако / China",
    note: "Оригинал потребуется при регистрации",
  },
  {
    id: "jw202",
    title: "Форма JW202",
    category: "study",
    status: "ready",
    expiresAt: "31.12.2026",
    contact: "Университет",
    location: "Папка документов",
    note: "Не сдавать единственный оригинал без копии",
  },
  {
    id: "insurance",
    title: "Медицинская страховка",
    category: "health",
    status: "missing",
    expiresAt: "01.09.2027",
    contact: "",
    location: "",
    note: "Уточнить покрытие на территории КНР",
  },
  {
    id: "dorm",
    title: "Подтверждение общежития",
    category: "housing",
    status: "preparing",
    expiresAt: "31.10.2026",
    contact: "Dormitory Office",
    location: "",
    note: "Оплата только за первые два месяца",
  },
];
